# https://alacritty.org/config-alacritty.html

[colors.bright]
black = "#666666"
blue = "#6699ff"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#ffffff"
yellow = "#e7c547"

[colors.normal]
black = "#2c2c2c"
blue = "#5ab6ef"
cyan = "#1bb8b8"
green = "#c9ea5a"
magenta = "#c397d8"
red = "#ff6666"
white = "#ebebeb"
yellow = "#ffd30a"

[colors.primary]
background = "#131516"
foreground = "#c0c3c1"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[terminal]

[terminal.shell]
program = "/usr/bin/env"
args = ["tmux"]
# args = ["tmux", "new", "/bin/zsh"]
# args = ["arch", "-arm64", "/bin/zsh"]
# program = "/bin/zsh"
# /usr/bin/arch -arm64 /bin/zsh
# program = "/usr/bin/arch"
# args = ["-arm64", "/bin/zsh"]

[window]
option_as_alt = "Both"

[window.dimensions]
columns = 180
lines = 50

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001B[1;6I"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001B[1;5I"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
key = "S"
mods = "Alt"
chars = "\u001Bs"

[[keyboard.bindings]]
key = "T"
mods = "Alt"
chars = "\u001Bt"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001F"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

# macのJISキーボードでbackslashを入力すると円マークが入力されてしまうのでマッピング
[[keyboard.bindings]]
key = "¥"
chars = "\\"
